### ISSUE TITLE
Copied

### ISSUE THREAD

**Issue by aayushgenius** [sayantanm19/js-simple-typing-game#1]
Hey, I just wanted to say that I saw this code being copied without credit. The link to it is https://github.com/NightZan999/Your-Coding-Journey/tree/master/Games/Speed%20Test%20Game. He may have accidentally done this.

**Comment by aayushgenius** [comment]
@sayantanm19

**Comment by sayantanm19** [comment]
I apologize for the late closure. Thank you for bringing it to my notice and following up. The repository seems to be deleted now so he might have accidentally done it. Anyways, thank you again.
