### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by qwertyist** [sayantanm19/js-simple-typing-game#2]
I looked at this code which seems to be a great template to work from when I'm creating a learning tool for subtitling students.
I wonder if the code is free of use? What license can I use it under? Of course I will reference your guide at GeeksforGeeks and this repo.

**Comment by sayantanm19** [comment]
You can use the code as you like under the MIT License. It is great to see being used as a template for students! The article content from GeeksforGeeks has separate copyright rules that you can check on the website.
